name: e2e
on:
  push:
    branches: [ master ]
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: e2e-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: e2e-yarn-
      - run: yarn
  Linux:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome,firefox]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore node_modules cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: e2e-yarn-${{ hashFiles('**\yarn.lock') }}
          restore-keys: e2e-yarn-
      - run: yarn
      - name: Run test
        run: yarn test:e2e
        env:
          BROWSER: ${{ matrix.browser }}
